#!/bin/bash
echo '#!/bin/bash' > 0-preprocessor
echo '#!/bin/bash' > 1-compiler
echo '#!/bin/bash' > 2-assembler
echo '#!/bin/bash' > 3-name
echo '#!/bin/bash' > 4-puts.c
echo '#!/bin/bash' > 5-printf.c
echo '#!/bin/bash' > 6-size.c
